### ISSUE TITLE
Cannot install packages (travis only) when this package is in the requirements.

### ISSUE THREAD

**Issue by vangorra** [carsongee/pytest-pylint#102]
It appears to have a version conflict with six. Which is weird considering this project doesn't pin the version and the venv build works locally but the venv build on travis fails.

Any method to get this working?

Here's the build showing the error:
https://travis-ci.org/vangorra/python_withings_api/jobs/594694196

Here's the error:
```
Using /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages
Searching for six==1.12.0
Best match: six 1.12.0
Processing six-1.12.0-py3.7.egg
Adding six 1.12.0 to easy-install.pth file
Using /home/travis/build/vangorra/python_withings_api/.eggs/six-1.12.0-py3.7.egg
Finished processing dependencies for withings-api==0.0.0a0
  File "build/bdist.linux-x86_64/egg/oauth_hook/hook.py", line 93
    except TypeError, e:
                    ^
SyntaxError: invalid syntax
  File "build/bdist.linux-x86_64/egg/tests/tests.py", line 111
    print "Go to https://api.twitter.com/oauth/authenticate?oauth_token=%s and sign in into the application, then enter your PIN" % oauth_token[0]
                                                                                                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Go to https://api.twitter.com/oauth/authenticate?oauth_token=%s and sign in into the application, then enter your PIN" % oauth_token[0])?
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests_oauth-0.4.1-py3.7.egg/oauth_hook/hook.py", line 93
    except TypeError, e:
                    ^
SyntaxError: invalid syntax
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests_oauth-0.4.1-py3.7.egg/tests/tests.py", line 111
    print "Go to https://api.twitter.com/oauth/authenticate?oauth_token=%s and sign in into the application, then enter your PIN" % oauth_token[0]
                                                                                                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Go to https://api.twitter.com/oauth/authenticate?oauth_token=%s and sign in into the application, then enter your PIN" % oauth_token[0])?
Running tests.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.11.0 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('six==1.12'), {'astroid'})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    "Programming Language :: Python :: Implementation :: PyPy",
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.7.1/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/travis/build/vangorra/python_withings_api/.eggs/pytest_runner-5.1-py3.7.egg/ptr.py", line 209, in run
    return self.run_tests()
  File "/home/travis/build/vangorra/python_withings_api/.eggs/pytest_runner-5.1-py3.7.egg/ptr.py", line 220, in run_tests
    result_code = __import__('pytest').main()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 195, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 654, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 871, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 816, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 273, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'pylint' could not be loaded: (six 1.11.0 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('six==1.12'), {'astroid'})!
The command "./scripts/build.sh" exited with 1.
```

**Comment by carsongee** [comment]
Hi, thanks for reporting this.  My best guess is that another package in your set up has pinned six to that version.  I'm afraid you're probably going to have to go on a bit of a deep dive across your dependencies to find the culprit.

**Comment by tseader** [comment]
Astroid issue related to this [here](https://github.com/PyCQA/astroid/issues/718).

**Comment by tseader** [comment]
When isolating in a clean/new virtual environment, the following dump occurs:
```shell
Collecting pytest-pylint
  Using cached https://files.pythonhosted.org/packages/64/dc/6f35f114844fb12e38d60c4f3d2441a55baff7043ad4e013777dff55746c/pytest_pylint-0.14.1-py3-none-any.whl
Collecting six (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting pylint>=1.4.5 (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/ea/f1/758de486e46ea2b8717992704b0fdd968b7cbc2bc790b976fae4a35a212c/pylint-2.4.3-py3-none-any.whl
Collecting pytest>=2.7 (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/93/16/f6dec5178f5f4141e80dfc4812a9aba88f5f29ca881f174ab1851181d016/pytest-5.2.2-py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting astroid<2.4,>=2.3.0 (from pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/64/d3/4ba68bd56297556c9c2e5072d71d1664feaa86d9726c237a9fe496d440f4/astroid-2.3.2-py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl
Collecting packaging (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting wcwidth (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Collecting wrapt==1.11.* (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint)
Collecting lazy-object-proxy==1.4.* (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/0b/dd/b1e3407e9e6913cf178e506cd0dee818e58694d9a5cd1984e3f6a8b9a10f/lazy_object_proxy-1.4.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/31/d3/9d1802c161626d0278bafb1ffb32f76b9d01e123881bbf9d91e8ccf28e18/typed_ast-1.4.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->pytest>=2.7->pytest-pylint)
  Downloading https://files.pythonhosted.org/packages/a3/c4/7828cf9e71ce8fbd43c1e502f3fdd0498f069fcf9d1c268205ce278ae201/pyparsing-2.4.4-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 461kB/s 
astroid 2.3.2 has requirement six==1.12, but you'll have six 1.13.0 which is incompatible.
Installing collected packages: six, isort, wrapt, lazy-object-proxy, typed-ast, astroid, mccabe, pylint, more-itertools, zipp, importlib-metadata, atomicwrites, attrs, pluggy, pyparsing, packaging, wcwidth, py, pytest, pytest-pylint
Successfully installed astroid-2.3.2 atomicwrites-1.3.0 attrs-19.3.0 importlib-metadata-0.23 isort-4.3.21 lazy-object-proxy-1.4.3 mccabe-0.6.1 more-itertools-7.2.0 packaging-19.2 pluggy-0.13.0 py-1.8.0 pylint-2.4.3 pyparsing-2.4.4 pytest-5.2.2 pytest-pylint-0.14.1 six-1.13.0 typed-ast-1.4.0 wcwidth-0.1.7 wrapt-1.11.2 zipp-0.6.0
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

pipdeptree helps me visualize:
```shell
$ pipdeptree -fl
Warning!!! Possibly conflicting dependencies found:
* astroid==2.3.2
 - six [required: ==1.12, installed: 1.13.0]
------------------------------------------------------------------------
pipdeptree==0.13.2
  pip==18.1
pytest-pylint==0.14.1
  pylint==2.4.3
    astroid==2.3.2
      lazy-object-proxy==1.4.3
      six==1.13.0
      typed-ast==1.4.0
      wrapt==1.11.2
    isort==4.3.21
    mccabe==0.6.1
  pytest==5.2.2
    atomicwrites==1.3.0
    attrs==19.3.0
    importlib-metadata==0.23
      zipp==0.6.0
        more-itertools==7.2.0
    more-itertools==7.2.0
    packaging==19.2
      pyparsing==2.4.4
      six==1.13.0
    pluggy==0.13.0
      importlib-metadata==0.23
        zipp==0.6.0
          more-itertools==7.2.0
    py==1.8.0
    wcwidth==0.1.7
  six==1.13.0
setuptools==40.6.2
```

**Comment by tseader** [comment]
Interesting find when setting up two scenarios with a fresh venv - installing pylint then pytest-pylint results in no incompatibility issue, whereas installing just pytest-pylint results in an issue. 

I'm not convinced this is an issue that pytest-pylint is responsible for, however, I wonder if re-arranging the dependencies in the setup.py from `install_requires=['pytest>=2.7', 'pylint>=1.4.5', 'six'],` to `install_requires=['pylint>=1.4.5', 'pytest>=2.7', 'six'],` would resolve the issue.  I think it's a bit hacky as the issue I believe is really on Astroid's decision to pin `six==1.12`, which should be resolved soon (I hope)

## Fresh Venv env pip install tests:
### Works
pip install pylint --no-cache
pip install pytest-pylint --no-cache

### Version Incompatibility issue with six
pip install pytest-pylint --no-cache

### Version Incompatibility issue with six
pip install pytest --no-cache
pip install pytest-pylint --no-cache


## Dumped Details on the Scenarios referenced above

#### Scenario 1 - pylint then pytest-pylint
*Result* - No compatibility issue
```shell
(v2) $ pipdeptree -fl
pipdeptree==0.13.2
  pip==18.1
setuptools==40.6.2

(v2) $ pip install pylint
Looking in indexes: https://pypi.org/simple, https://nexus.cs.zionsbank.com/repository/pypi-all/
Collecting pylint
  Using cached https://files.pythonhosted.org/packages/ea/f1/758de486e46ea2b8717992704b0fdd968b7cbc2bc790b976fae4a35a212c/pylint-2.4.3-py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint)
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting astroid<2.4,>=2.3.0 (from pylint)
  Using cached https://files.pythonhosted.org/packages/64/d3/4ba68bd56297556c9c2e5072d71d1664feaa86d9726c237a9fe496d440f4/astroid-2.3.2-py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" (from astroid<2.4,>=2.3.0->pylint)
  Using cached https://files.pythonhosted.org/packages/31/d3/9d1802c161626d0278bafb1ffb32f76b9d01e123881bbf9d91e8ccf28e18/typed_ast-1.4.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting six==1.12 (from astroid<2.4,>=2.3.0->pylint)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting wrapt==1.11.* (from astroid<2.4,>=2.3.0->pylint)
Collecting lazy-object-proxy==1.4.* (from astroid<2.4,>=2.3.0->pylint)
  Using cached https://files.pythonhosted.org/packages/0b/dd/b1e3407e9e6913cf178e506cd0dee818e58694d9a5cd1984e3f6a8b9a10f/lazy_object_proxy-1.4.3-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: isort, typed-ast, six, wrapt, lazy-object-proxy, astroid, mccabe, pylint
Successfully installed astroid-2.3.2 isort-4.3.21 lazy-object-proxy-1.4.3 mccabe-0.6.1 pylint-2.4.3 six-1.12.0 typed-ast-1.4.0 wrapt-1.11.2
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(v2) $ pip install pytest-pylint
Looking in indexes: https://pypi.org/simple, https://nexus.cs.zionsbank.com/repository/pypi-all/
Collecting pytest-pylint
  Using cached https://files.pythonhosted.org/packages/64/dc/6f35f114844fb12e38d60c4f3d2441a55baff7043ad4e013777dff55746c/pytest_pylint-0.14.1-py3-none-any.whl
Requirement already satisfied: six in ./v2/lib/python3.6/site-packages (from pytest-pylint) (1.12.0)
Requirement already satisfied: pylint>=1.4.5 in ./v2/lib/python3.6/site-packages (from pytest-pylint) (2.4.3)
Collecting pytest>=2.7 (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/93/16/f6dec5178f5f4141e80dfc4812a9aba88f5f29ca881f174ab1851181d016/pytest-5.2.2-py3-none-any.whl
Requirement already satisfied: mccabe<0.7,>=0.6 in ./v2/lib/python3.6/site-packages (from pylint>=1.4.5->pytest-pylint) (0.6.1)
Requirement already satisfied: isort<5,>=4.2.5 in ./v2/lib/python3.6/site-packages (from pylint>=1.4.5->pytest-pylint) (4.3.21)
Requirement already satisfied: astroid<2.4,>=2.3.0 in ./v2/lib/python3.6/site-packages (from pylint>=1.4.5->pytest-pylint) (2.3.2)
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl
Collecting wcwidth (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting packaging (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: lazy-object-proxy==1.4.* in ./v2/lib/python3.6/site-packages (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint) (1.4.3)
Requirement already satisfied: wrapt==1.11.* in ./v2/lib/python3.6/site-packages (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint) (1.11.2)
Requirement already satisfied: typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" in ./v2/lib/python3.6/site-packages (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint) (1.4.0)
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/a3/c4/7828cf9e71ce8fbd43c1e502f3fdd0498f069fcf9d1c268205ce278ae201/pyparsing-2.4.4-py2.py3-none-any.whl
Installing collected packages: more-itertools, zipp, importlib-metadata, atomicwrites, pluggy, wcwidth, pyparsing, packaging, py, attrs, pytest, pytest-pylint
Successfully installed atomicwrites-1.3.0 attrs-19.3.0 importlib-metadata-0.23 more-itertools-7.2.0 packaging-19.2 pluggy-0.13.0 py-1.8.0 pyparsing-2.4.4 pytest-5.2.2 pytest-pylint-0.14.1 wcwidth-0.1.7 zipp-0.6.0
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(v2) $ pipdeptree -fl
pipdeptree==0.13.2
  pip==18.1
pytest-pylint==0.14.1
  pylint==2.4.3
    astroid==2.3.2
      lazy-object-proxy==1.4.3
      six==1.12.0
      typed-ast==1.4.0
      wrapt==1.11.2
    isort==4.3.21
    mccabe==0.6.1
  pytest==5.2.2
    atomicwrites==1.3.0
    attrs==19.3.0
    importlib-metadata==0.23
      zipp==0.6.0
        more-itertools==7.2.0
    more-itertools==7.2.0
    packaging==19.2
      pyparsing==2.4.4
      six==1.12.0
    pluggy==0.13.0
      importlib-metadata==0.23
        zipp==0.6.0
          more-itertools==7.2.0
    py==1.8.0
    wcwidth==0.1.7
  six==1.12.0
setuptools==40.6.2
```

#### Scenario 2 - pytest-pylint first and only
*Result* - Version incompatibility
```shell
(v2) $ pipdeptree -fl
pipdeptree==0.13.2
  pip==18.1
setuptools==40.6.2

(v2) $ pip install pytest-pylint
Looking in indexes: https://pypi.org/simple, https://nexus.cs.zionsbank.com/repository/pypi-all/
Collecting pytest-pylint
  Using cached https://files.pythonhosted.org/packages/64/dc/6f35f114844fb12e38d60c4f3d2441a55baff7043ad4e013777dff55746c/pytest_pylint-0.14.1-py3-none-any.whl
Collecting six (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting pytest>=2.7 (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/93/16/f6dec5178f5f4141e80dfc4812a9aba88f5f29ca881f174ab1851181d016/pytest-5.2.2-py3-none-any.whl
Collecting pylint>=1.4.5 (from pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/ea/f1/758de486e46ea2b8717992704b0fdd968b7cbc2bc790b976fae4a35a212c/pylint-2.4.3-py3-none-any.whl
Collecting packaging (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting wcwidth (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting astroid<2.4,>=2.3.0 (from pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/64/d3/4ba68bd56297556c9c2e5072d71d1664feaa86d9726c237a9fe496d440f4/astroid-2.3.2-py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/a3/c4/7828cf9e71ce8fbd43c1e502f3fdd0498f069fcf9d1c268205ce278ae201/pyparsing-2.4.4-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=2.7->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.4.* (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/0b/dd/b1e3407e9e6913cf178e506cd0dee818e58694d9a5cd1984e3f6a8b9a10f/lazy_object_proxy-1.4.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting wrapt==1.11.* (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint)
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" (from astroid<2.4,>=2.3.0->pylint>=1.4.5->pytest-pylint)
  Using cached https://files.pythonhosted.org/packages/31/d3/9d1802c161626d0278bafb1ffb32f76b9d01e123881bbf9d91e8ccf28e18/typed_ast-1.4.0-cp36-cp36m-manylinux1_x86_64.whl

astroid 2.3.2 has requirement six==1.12, but you'll have six 1.13.0 which is incompatible.

Installing collected packages: six, pyparsing, packaging, wcwidth, py, more-itertools, attrs, zipp, importlib-metadata, atomicwrites, pluggy, pytest, isort, lazy-object-proxy, wrapt, typed-ast, astroid, mccabe, pylint, pytest-pylint
Successfully installed astroid-2.3.2 atomicwrites-1.3.0 attrs-19.3.0 importlib-metadata-0.23 isort-4.3.21 lazy-object-proxy-1.4.3 mccabe-0.6.1 more-itertools-7.2.0 packaging-19.2 pluggy-0.13.0 py-1.8.0 pylint-2.4.3 pyparsing-2.4.4 pytest-5.2.2 pytest-pylint-0.14.1 six-1.13.0 typed-ast-1.4.0 wcwidth-0.1.7 wrapt-1.11.2 zipp-0.6.0

(v2)$ pipdeptree -fl
Warning!!! Possibly conflicting dependencies found:
* astroid==2.3.2
 - six [required: ==1.12, installed: 1.13.0]
------------------------------------------------------------------------
pipdeptree==0.13.2
  pip==18.1
pytest-pylint==0.14.1
  pylint==2.4.3
    astroid==2.3.2
      lazy-object-proxy==1.4.3
      six==1.13.0
      typed-ast==1.4.0
      wrapt==1.11.2
    isort==4.3.21
    mccabe==0.6.1
  pytest==5.2.2
    atomicwrites==1.3.0
    attrs==19.3.0
    importlib-metadata==0.23
      zipp==0.6.0
        more-itertools==7.2.0
    more-itertools==7.2.0
    packaging==19.2
      pyparsing==2.4.4
      six==1.13.0
    pluggy==0.13.0
      importlib-metadata==0.23
        zipp==0.6.0
          more-itertools==7.2.0
    py==1.8.0
    wcwidth==0.1.7
  six==1.13.0
setuptools==40.6.2
```

**Comment by tseader** [comment]
Workaround is documented in the root issue [here](https://github.com/PyCQA/astroid/issues/718)

**Comment by tseader** [comment]
[Astroid](https://github.com/PyCQA/astroid/pull/719) has been updated, which should resolve this issue.
