### ISSUE TITLE
Pylint 3.0.0 breaking changes - ImportError: cannot import name 'IReporter' from 'pylint.interfaces'

### ISSUE THREAD

**Issue by reyes-c1** [carsongee/pytest-pylint#180]
Since this appears to be an integration problem between libraries, not sure if this is the best place to address it but you have to start somewhere and this library is at the bottom of the call stack... When I use the new Pylint 3.0.0 I get the following error when I do `pipenv run pytest tests`. If I switch back to the Pylint 2.17.6 version I don't get the error.

```
pipenv run pytest tests
Traceback (most recent call last):
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/config/__init__.py", line 192, in console_main
    code = main()
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/config/__init__.py", line 150, in main
    config = _prepareconfig(args, plugins)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/config/__init__.py", line 331, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pluggy/_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/helpconfig.py", line 104, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1305, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/redacted-user/.pyenv/versions/3.8.13/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/redacted-user/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pytest_pylint/plugin.py", line 18, in <module>
    from .pylint_util import ProgrammaticReporter
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pytest_pylint/pylint_util.py", line 5, in <module>
    from pylint.interfaces import IReporter
ImportError: cannot import name 'IReporter' from 'pylint.interfaces' (/Users/redacted-user/.local/share/virtualenvs/redacted-project-0JGbq0V4/lib/python3.8/site-packages/pylint/interfaces.py)
```

Let me know what you think or if you need more info. Thanks!

**Comment by reyes-c1** [comment]
It looks like this is already removed on the main branch but was still there on the v0.19 tagged branch which matches the release version I see in PyPi, so looks like this has already been fixed but is just waiting for the next release. Is a release in the works?

**Comment by carsongee** [comment]
Odd, I thought I already released from main. I'll plan to push out 0.20.0 shortly.

**Comment by carsongee** [comment]
0.20.0 is released!
