### ISSUE TITLE
Crashes with pytest 8.1

### ISSUE THREAD

**Issue by WolfgangFellger** [carsongee/pytest-pylint#192]
Any attempt to load the plugin immediately crashes with pytest 8.1, same setup working fine with 8.0.2.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/_pytest/main.py", line 280, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1119, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 523, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 138, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pytest_pylint/plugin.py", line 84, in pytest_configure
INTERNALERROR>     config.pluginmanager.register(pylint_plugin)
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 497, in register
INTERNALERROR>     plugin_name = super().register(plugin, name)
INTERNALERROR>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 167, in register
INTERNALERROR>     self._verify_hook(hook, hookimpl)
INTERNALERROR>   File "/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 342, in _verify_hook
INTERNALERROR>     raise PluginValidationError(
INTERNALERROR> pluggy._manager.PluginValidationError: Plugin '139870918328976' for hook 'pytest_collect_file'
INTERNALERROR> hookimpl definition: pytest_collect_file(path, parent)
INTERNALERROR> Argument(s) {'path'} are declared in the hookimpl but can not be found in the hookspec
```

This seems to be caused by https://docs.pytest.org/en/stable/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path et al being only _actually_ [removed since 8.1](https://github.com/pytest-dev/pytest/issues/12061#issuecomment-1975884131), which just released.

**Comment by WolfgangFellger** [comment]
Since I opened this issue pytest 8.1.0 has been yanked and they have decided to let this feature live til 9.0, so this is not urgent anymore.
