### ISSUE TITLE
cache property not available

### ISSUE THREAD

**Issue by sambrightman** [carsongee/pytest-pylint#91]
I'm getting this when running `teamcity-messages` tests for pylint:

```
Traceback (most recent call last):
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/_pytest/main.py", line 80, in wrap_session
     config.do_configure()
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/_pytest/config.py", line 618, in do_configure
     self.hook.pytest_configure(config=self)
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
     return self._docall(self.methods, kwargs)
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
     firstresult=self.firstresult).execute()
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
     res = method(*args)
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/pytest_pylint.py", line 164, in pytest_configure
     config.pylint = PylintPlugin(config)
   File "/tmp/teamcity-python-venv/27pyst27pynt/lib/python2.7/site-packages/pytest_pylint.py", line 176, in __init__
     self.mtimes = config.cache.get(HISTKEY, {})
 AttributeError: 'Config' object has no attribute 'cache'
```

which appears to be related to #83. Maybe https://github.com/pytest-dev/pytest/commit/e478f66d8b9d0e25af7aa4695192bf1adf063ba4 is related? I can't see why the `cacheprovider` has not yet set the `cache` property, since it should be loaded first.

**Comment by orf** [comment]
We ran into this while running pytest with `-p no:cacheprovider`. Removing this fixed it.

**Comment by cs-cordero** [comment]
I also ran this while running pytest with `-p no:cacheprovider`.  I think it'd be a good idea to allow users to disable the cache if we wanted to.
